# Generated by Django 4.2.7 on 2023-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product_details',
            name='price',
            field=models.FloatField(),
        ),
    ]
